apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-sample-node-deployment
  labels:
    app: eks-sample-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-sample-node-app
  template:
    metadata:
      labels:
        app: eks-sample-node-app
    spec:
      containers:
      - name: hello-world
        image: REPO_URL
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: IfNotPresent
